# Generated by Django 6.0.5 on 2026-05-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('subtitulo', models.TextField(blank=True)),
                ('imagen_url', models.URLField(blank=True)),
                ('href', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_titulo', models.CharField(blank=True, max_length=160)),
                ('hero_subtitulo', models.TextField(blank=True)),
                ('hero_cta_texto', models.CharField(blank=True, max_length=80)),
                ('hero_cta_href', models.CharField(blank=True, max_length=200)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('texto', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('orden', 'id'),
            },
        ),
    ]
