# Generated by Django 6.0.5 on 2026-07-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_reserva_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='dias_disponibles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
