# Generated by Django 6.0.5 on 2026-07-07 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_servicio_dias_disponibles'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], unique=True)),
                ('abierto', models.BooleanField(default=True)),
                ('hora_inicio', models.TimeField(default=datetime.time(9, 0))),
                ('hora_fin', models.TimeField(default=datetime.time(21, 0))),
            ],
            options={
                'ordering': ['dia_semana'],
            },
        ),
    ]
