# Generated by Django 5.2.13 on 2026-07-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_diaexcepcion'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=('fecha', 'hora'), name='reserva_activa_unica_por_fecha_hora'),
        ),
    ]
