# Generated by Django 5.2.13 on 2026-07-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_reserva_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
