# Generated by Django 5.2.13 on 2026-07-08 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_servicio_horarios_dias_vigencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioExcepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('abierto', models.BooleanField(default=False)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=140)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='agenda.servicio')),
            ],
            options={
                'ordering': ['fecha'],
                'constraints': [models.UniqueConstraint(fields=('servicio', 'fecha'), name='servicio_excepcion_unica_por_fecha')],
            },
        ),
    ]
