# Generated by Django 6.0.5 on 2026-05-30 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría Blog',
                'verbose_name_plural': 'Categorías Blog',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('extracto', models.TextField(blank=True)),
                ('contenido', models.TextField(blank=True)),
                ('imagen_url', models.URLField(blank=True)),
                ('publicado', models.BooleanField(default=False)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.categoriablog')),
            ],
            options={
                'ordering': ('-publicado_en', '-creado_en'),
            },
        ),
    ]
